<% 
response.setHeader("Pragma","no-cache"); 
response.setHeader("Cache-Control","no-store"); 
response.setHeader("Expires","0"); 
response.setDateHeader("Expires",-1); 
session.removeAttribute("adminname");
session.invalidate();
response.sendRedirect("index.jsp");
%>